language: generic
env:
  - PY_VERS="3.6"
before_install:
  - wget "https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh" -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b  -p /home/travis/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
install:
  - conda install --yes python=$PY_VERS pytorch torchvision cudatoolkit=10.0 -c pytorch pip
  - "pip install -U pip"
  - "pip install pytest"
  - "python install -e ."
# - "pip install pytest-timeout"
script: pytest