language: python
python:
  - "3.6"
cache: pip
install:
  -  pip install -U pip
  -  pip install https://download.pytorch.org/whl/cu100/torch-1.1.0-cp36-cp36m-linux_x86_64.whl
  -  pip install https://download.pytorch.org/whl/cu100/torchvision-0.3.0-cp36-cp36m-linux_x86_64.whl
  -  pip install pytorch-ignite
  -  pip install pytest
  -  pip install -e .
script: 
  - source loadTestData.sh
  - pytest test/
